### ISSUE TITLE
"ModuleNotFound: plaquette_graph_bindings" when installing the code in the branch ssc/api

### ISSUE THREAD

**Issue by mattsantand** [qc-design/plaquette#29]
**Describe the bug**
After successful installation of the branch code in a clean venv, I receive the error 
`ModuleNotFoundError: No module named 'plaquette_graph_bindings'`
when importing plaquette.

**Minimal Working Example**

1. Clone the repo and checkout the ssc/api branch
2. In a new venv, run `pip install \path\to\cloned\repo\plaquette --pre`
3. After successful installation of all packages, in the new venv, try to run `import plaquette`

**Expected behavior**

**Traceback**
<details>
<summary> Traceback </summary>

```
Traceback (most recent call last):
  File "C:\Users\matte\Documents\QCDesign\pythonProject\test_plaquette_api\mwe.py", line 1, in <module>
    from plaquette import codes, decoders, pauli
  File "C:\Users\matte\Documents\QCDesign\Repository\plaquette\src\plaquette\__init__.py", line 27, in <module>
    from plaquette.device import Device  # noqa: F401
  File "C:\Users\matte\Documents\QCDesign\Repository\plaquette\src\plaquette\device\__init__.py", line 40, in <module>
    from plaquette import circuit as plaq_circuit
  File "C:\Users\matte\Documents\QCDesign\Repository\plaquette\src\plaquette\circuit\__init__.py", line 25, in <module>
    from plaquette.circuit.generator import generate_qec_circuit  # noqa: F401
  File "C:\Users\matte\Documents\QCDesign\Repository\plaquette\src\plaquette\circuit\generator.py", line 10, in <module>
    from plaquette import circuit, codes, pauli
  File "C:\Users\matte\Documents\QCDesign\Repository\plaquette\src\plaquette\codes\__init__.py", line 17, in <module>
    from plaquette_graph import MultiGraph, SparseGraph
  File "C:\Users\matte\Documents\QCDesign\pythonProject\test_plaquette_api\venv\lib\site-packages\plaquette_graph\__init__.py", line 2, in <module>
    from plaquette_graph_bindings import SparseGraphRow
ModuleNotFoundError: No module named 'plaquette_graph_bindings'
```

</details>

**Plaquette version:**
Commit hash: 9b857f68c732d8a7095b31b8e565a73cc8dfd904

**Additional context**

**Comment by massarom** [comment]
Mmm I can't reproduce that. I did the following

```sh
# Make random folder for testing
mkdir playground && cd playground
python3.10 -m venv .venv
source .venv/bin/activate
# Grab code from commit cited in issue
pip install git+https://github.com/qc-design/plaquette.git@9b857f68c732d8a7095b31b8e565a73cc8dfd904
# Shorthand to run a single line of python
python -c 'import plaquette'
```

I also tested opening a python session, and also there it worked. The only weird thing is that on first import it took a _lot_ of time to finish (some 7-10 seconds!) but no errors.

I can also run directly the line mentioned in the Traceback as the culprit

```sh
python -c 'from plaquette_graph_bindings import SparseGraphRow'
```

but no errors.

I'm doing everything on macOS. If you're on Windows, can you try running it in the [WSL2](https://learn.microsoft.com/en-us/windows/wsl/)?

**Comment by mattsantand** [comment]
Ok, it looks like a Windows bug, as far as I can tell. 

I tried to use your commands on a windows terminal (previously I was using PyCharm) and I got the same error as in OP.

I tried to do the same in WSL and I had no issue.

**Comment by massarom** [comment]
OK good to know.

As a sanity check, does the same problem happen with the master branch?

**Comment by mattsantand** [comment]
On Windows, I just installed the main branch (`pip install git+https://github.com/qc-design/plaquette`) in a new venv and there seem to no issues.
